error: remove GetLastError() function
The virGetLastError() function fetches the last reported error from a
thread local variable. Goroutines may be arbitrarily switched between OS
threads between the libvirt API call and the virGetLastError()
call. Thus this API is impossible to use safely and must be removed. All
the Go APIs return an error object directly so nothing should need the
GetLastError() binding anyway.

Signed-off-by: Daniel P. Berrangé <berrange@redhat.com>